### ISSUE TITLE
PHP files will not work?

### ISSUE THREAD

**Issue by xXAndrew28Xx** [sintaxi/surge#183]
I have this test game website and it keeps spamming in my browser console:
POST *MY DOMAIN*.com/main.php 404 (Not found)
I am sure main.php is in the directory I ran 'surge' in.

**Comment by RodrigoHahn** [comment]
Not the maintainer, but *no.*

Surge was built from the ground up as a CDN-backed, *static site*
hosting/publishing solution. While you can use it as part of a more
sophisticated build process if you want, the focus is getting your static
assets (HTML/CSS/JS) online quickly. You can still have dynamic content,
work with secure authentication, call APIs, configure routing, consume web
services and take advantage of most benefits available to dynamic sites,
but since it assumes a static site structure, you cannot use traditional
server-side scripting like PHP, Python and similar.

Rodrigo Machado Hahn
