### ISSUE TITLE
Support for downloading projects [request]

### ISSUE THREAD

**Issue by midudev** [sintaxi/surge#192]
It might sound a bit weird the request but as soon as you have some projects working on, sometimes you want to be sure that in some moment you'll be able to download all the website. I would like to have a way to download the project from surge with a single client command.

**Comment by kennethormandy** [comment]
Hey, thanks for opening an issue. Can you give us some more background on why you’d like that to be part of Surge?

So far, we have intentionally avoided adding this because we’d rather encourage some kind of version control system—git, Dropbox, whatever—for source files, rather than relying on getting their compiled HTML, CSS, and JavaScript back off of Surge.

**Comment by miduga** [comment]
Thanks to your for an awesome tool. :)

Yeah, maybe it's kinda of weird the request as I'm using Dropbox (far from ideal, I know). The thing is, yesterday I uploaded a website to surge from my laptop (OSX). Today I forgot my laptop on the office and I had my desktop computer with Linux. I wanted to make a minor improvement in the website but, problem is Drobpox in Ubuntu is a pain and I though to download the website. As you have to upload the entire website to surge in order to update, downloading from Dropbox website wasn't an option.

So, just to be clear, is not critical for me, it's only I missed the functionality today. I'm moving my code to github but I thought that maybe could be a minor future feature to be considered. :+1:

**Comment by OAGr** [comment]
I would second this as a minor feature.

Basically, I want to make sure that what is deployed to production is exactly what was deployed on my staging environment, but I want to be able to deploy both from different machines and don't want to care about local machine state.

**Comment by lovellfelix** [comment]
+1

**Comment by yubathom** [comment]
+1

**Comment by EliotSlevin** [comment]
I'd also find this useful. The other day I deployed a site and forgot to chuck it in github or something. Downloading would be great in this instance.

**Comment by TrentSterling** [comment]
Needed this today, searched around and find its not an option yet? **Oof**.

**Comment by Sant268** [comment]
..another year up.
I see why they wouldn't want to encourage this, it makes sense from their bandwidth perspective as well.
Minor feature, but can be misused and bad for their infra.
We can still hope this arrives, maybe

**Comment by lucastnr** [comment]
I think this would be a great addition to surge, needed an older version of a project that was on surge, unfortunately this is not available till now.

**Comment by EliotSlevin** [comment]
Hi, I'd like to yet again ask for this feature, and ask for this issue to be reopened. 

Surge.sh was a way I deployed heaps of small little things I was playing with while I was at university. Over the last 7 years I've deployed 96 surge sites. In a weird way they represent a time in my life, where I was just starting out, growing and getting better. I never used git at the time, because frankly I didn't know how to use it at the time. I was new remember. 

I'd love to be able to save these sites for my own personal archive of work. Just for the memories. While surge is a well run service, I could loose my email, I could loose my account, surge may shut down sometime. 

@midudev, I see this issue was closed as completed, yet I can't find any documentation about an export or download feature being added. Please consider re-opening.

**Comment by darnfish** [comment]
I would really appreciate this!

**Comment by hanoii** [comment]
```
export DOMAIN=... ; surge files $DOMAIN | sed -e 's/\x1b\[[0-9;]*m//g' | tr -s ' ' | cut -d ' ' -f 4 | sed "s/$DOMAIN\///g" | jq -Rr @uri | xargs -I {} wget -x -nH "$DOMAIN/{}"
```
