### ISSUE TITLE
Deku 404?

### ISSUE THREAD

**Issue by mythmon** [sintaxi/surge#220]
From [Deku](https://github.com/anthonyshort/deku), I clicked the link that said "You can read the documentation online.", which sent me to `http://anthonyshort.me/deku/`, which said "Hey, sorry for the trouble, but there’s nothing here. If you think there should be, feel free to open an issue on GitHub".

So I'm opening an issue.

**Comment by kennethormandy** [comment]
Hey, thanks. Looks like @anthonyshort started setting up the documentation on Surge, but doesn’t have anything there now. You could either open a PR at [anthonyshort/deku](https://github.com/anthonyshort/deku/) to remove the link you clicked from the README, or open an issue there to help get the existing site on Surge. But nothing is wrong with the Surge link, you’re just seeing the default 404 page since there’s no `index.html` or [custom 404 page](https://surge.sh/help/adding-a-custom-404-not-found-page) set.
