### ISSUE TITLE
Wrong SSL certificate is returned sometimes

### ISSUE THREAD

**Issue by diamondo25** [sintaxi/surge#242]
Sometimes, the SSL certificate for 1403.slantedhall.com is returned, instead of *.surge.sh.
The following party has recorded this online:
http://sium.co/kc1asd.com
http://sium.co/tegasaur.us
http://zium.co/kdcomputersolutions.net

I also notice this with the new Amsterdam IP:

```
➜  ... git:(master) ✗ curl https://188.166.132.94 -k -I -v
* Rebuilt URL to: https://188.166.132.94/
*   Trying 188.166.132.94...
* Connected to 188.166.132.94 (188.166.132.94) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.surge.sh
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: 188.166.132.94
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Server: SurgeCDN/0.12.2
Server: SurgeCDN/0.12.2
< Date: Mon, 12 Dec 2016 15:00:43 GMT
Date: Mon, 12 Dec 2016 15:00:43 GMT
< Connection: close
Connection: close
< Strict-Transport-Security: max-age=15768000
Strict-Transport-Security: max-age=15768000

<
* Closing connection 0
➜  ... git:(master) ✗ curl https://188.166.132.94 -k -I -v
* Rebuilt URL to: https://188.166.132.94/
*   Trying 188.166.132.94...
* Connected to 188.166.132.94 (188.166.132.94) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.surge.sh
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: 188.166.132.94
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Server: SurgeCDN/0.12.2
Server: SurgeCDN/0.12.2
< Date: Mon, 12 Dec 2016 15:00:44 GMT
Date: Mon, 12 Dec 2016 15:00:44 GMT
< Connection: close
Connection: close
< Strict-Transport-Security: max-age=15768000
Strict-Transport-Security: max-age=15768000

<
* Closing connection 0
➜  ... git:(master) ✗ curl https://188.166.132.94 -k -I -v
* Rebuilt URL to: https://188.166.132.94/
*   Trying 188.166.132.94...
* Connected to 188.166.132.94 (188.166.132.94) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: 1403.slantedhall.com
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: 188.166.132.94
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Server: SurgeCDN/0.12.2
Server: SurgeCDN/0.12.2
< Date: Mon, 12 Dec 2016 15:00:45 GMT
Date: Mon, 12 Dec 2016 15:00:45 GMT
< Connection: close
Connection: close
< Strict-Transport-Security: max-age=15768000
Strict-Transport-Security: max-age=15768000

<
* Closing connection 0

```

**Comment by diamondo25** [comment]
Screenshot of SSL Labs showing 2 certificates

<img width="745" alt="schermafbeelding 2016-12-12 om 16 16 44" src="https://cloud.githubusercontent.com/assets/39577/21104335/70ad8a46-c086-11e6-954f-7bc18fc99c8c.png">

**Comment by sintaxi** [comment]
Thanks for kicking the tires in our Amsterdam location. Looks like the fallback SSL cert wasn't set correctly. It will now fallback to use *.surge.sh cert.

**Comment by shakna-israel** [comment]
@sintaxi, not sure this one is resolved.

I'm getting a 1403.slantedhall.com cert on [squishelsandme.tk](http://squishelsandme.tk)

**Comment by sintaxi** [comment]
@shankna-israel - This can happen sometimes when a process hangs. I'll look into it.

Did you upload your own `.pem` file? Are you expecting https to work?

**Comment by shakna-israel** [comment]
I'm not expecting https to work, I'm not using SSL.. But it was redirecting to the https site.

**Comment by srobertson421** [comment]
@sintaxi @shakna-israel Did this get resolved? I'm getting the same issue with my domain

**Comment by shakna-israel** [comment]
@srobertson421 It disappeared after 24 hours. Not sure of the cause or the solution.

**Comment by allthesignals** [comment]
I'm seeing this issue as well. https://trailmap.mapc.org serves out the slantedhall.com cert. But it sounds like it resolves itself, after some time @shakna-israel @sintaxi

**Comment by gammons** [comment]
I also saw this issue.  My SSL was resolving to 1403.slantedhall.com for about 5 hours.  It resolved itself.

**Comment by allthesignals** [comment]
I love the Surge - it has been very helpful in my work. I went ahead and paid for the $13/month subscription so I could use SSL. Since posting about this issue, however, I haven't received any direct support from someone actually working for Surge (as far as I could tell). 

This was a time-sensitive issue for me. In order to resolve this issue with the confidence that I could have a finished product, our organization had to set up its own server to serve my app and the SSL cert correctly. 

At this point, I'm not sure if I should even try to switch back over to Surge due to the lack of support on this issue in particular (which is a paid feature). It's been an open issue since December. I understand that it just magically resolves itself for most users, but I like to feel confident that when I release something, it won't throw security warnings to my users and scare them away. 

That's not to say the community support hasn't been fantastic (it has been) - I just expected a little more at least in terms of communication from a paid subscription-based service. Digital Ocean is less expensive than this, and I can always feel confident that I'll get a response from them, no matter the issue.
