### ISSUE TITLE
'upload' is incomplete but surge said 'success'.

### ISSUE THREAD

**Issue by ghost** [sintaxi/surge#263]
> $ surge --project /use/surge/for/better/world/ --domain https://ilovesurge.surge.sh
> 
>     Surge - surge.sh
> 
>               email: hello@wor.ld
>               token: XXXXXXXXXXXXXXXX
>        project path: /use/surge/for/better/world/
>                size: 100 files, 50 MB
>              domain: https://ilovesurge.surge.sh
>              upload: [======              ] 29%, eta: 100.9s
>     Success! Project is published and running at ilovesurge.surge.sh
> 
> 
> events.js:72
>         throw er; // Unhandled 'error' event
>               ^
> Error: write EPIPE
>     at errnoException (net.js:904:11)
>     at Object.afterWrite (net.js:720:19)
> $ _

**Comment by proxyusertryingsurge** [comment]
Surge need this code

> if (upload_percent ==100){is_success=true;}

**Comment by brandonb927** [comment]
@ghost is this still an issue?

**Comment by lxgreen** [comment]
I also experience this issue. my main.js is about 2MB, but the uploaded file size is only 52KB

**Comment by sintaxi** [comment]
This shouldn't happen on later versions of surge. If you can provide some more info that would help starting with verifying the version of surge and OS you are on. 

Check if your main.js file is in a directory being ignored by surge. Such as `node_modules` .

Another suggestion I have is to check to see if the identifier changes beside the project when you run `surge list`. If so then then build did succeed and we just have a cache busting issue.

Overall this issue is very much unexpected ever since we overhauled how build confirmations work.
