### ISSUE TITLE
No logon or sign up prompt.

### ISSUE THREAD

**Issue by sarbazx** [sintaxi/surge#335]
Hi, first time using surge when running surge on macos 10.13.4 there no any command prompts. like this: 
![screen shot 2018-06-03 at 22 25 25](https://user-images.githubusercontent.com/5629946/40890346-3a9a58f4-677d-11e8-9816-2ee3a7139a41.png)

**Comment by sarbazx** [comment]
anybody?

**Comment by sintaxi** [comment]
Have you tried with a different terminal theme?

**Comment by sarbazx** [comment]
@sintaxi yes, same still.

**Comment by sintaxi** [comment]
ok, thanks for reporting. If you can provide any more information let me know.

**Comment by dimkir** [comment]
From your screenshot it seems that your cursor is somewhere one-third into line 7.  Which makes me believe that you _are_ prompted to input your email address. Albeit the prompt is invisible.   

Try typing into the prompt and if you can type, and when you press enter you get to next line then this would confirm the hypothesis. 

This should allow to redefine your original problem definition from:
> Hi, first time using surge when running surge on macos 10.13.4 there no any command prompts.

to 

> when running surge on macos 10.13.4 in a Terminal app XYZ with settings ABC the colored prompt of surge is displayed as invisible.


## ANSI code troubleshooting
This all hints at the fact that your terminal in current configuration has troubles displaying some ANSI codes. 

If you're looking to debug this issue further, you can try to run surge and redirect output to file. Later use this output to figure out which ANSI code was causing the trouble  (as in your case some ANSI codes were fine, because you can see formatted output of "Welcome To Surge").

```
# run this command, and press Cmd+C after that, later on inspect out.txt file
surge > out.txt 
```

This is what the expected output should look like:
![image](https://user-images.githubusercontent.com/3438798/42367692-f2841110-80fc-11e8-811a-213c5a486145.png)


And this is how contents of `out.txt` looks like:
![image](https://user-images.githubusercontent.com/3438798/42367781-3110d990-80fd-11e8-93dc-9f02bb138a99.png)


Your editor view may differ, but you can see in black the _escape_ sequence, followed by ANSI code of a color.  Most likely your terminal chokes somewhere around 2nd line: `^[[90m` characters. So you may want to manually edit file and remove all 6 of those characters and try to cat the file to the terminal to see if this helps. 

```
# this should print the file with all the colors 
cat out.txt
```

Hope this helps. 
ps. My screenshots are from Ubuntu, but the ANSI code principle is the same on Mac.

**Comment by sarbazx** [comment]
@sintaxi @dimkir Hi, thank for response, I have updated surge then tried again it successfully showed me the prompt.
