### ISSUE TITLE
Subdomain of a subdomain

### ISSUE THREAD

**Issue by timo-cmd2** [sintaxi/surge#459]
Hello everyone 👋🏻

I know that a DNS may hold as many as possible subdomains for a host. How can I configure this with surge.sh? Assuming, I have a webservice running on a site like pony.foo.surge.sh

Thanks for support and best regards

Timo Sarkar

**Comment by fu-sen** [comment]
You can't do it with `surge.sh`. Limited to `●●● .surge.sh`.
You can consider `●●●-●●●.surge.sh` instead of `●●●. ●●●.surge.sh`.
There are several reasons for this.
For example, the SSL certificate `*.surge.sh` does not target `●●●.●●●.surge.sh`.

If you use a custom domain, you should be able to use it without this limitation.

**Comment by timo-cmd2** [comment]
Alright perfect. Thanks!
