### ISSUE TITLE
Cannot access to my website

### ISSUE THREAD

**Issue by theadanielskocher** [sintaxi/surge#521]
I created my personal blog and deployed it on SURGE, but since yesterday I have not been able to access it. I want to ask you if there is any problem with my website? Thank you for your answer.

**Comment by McSloverd** [comment]
Yep, neither can I

**Comment by boson-higgs** [comment]
Same problem few days. I couldn't access even surge.sh, now surge.sh works but the hosted websites don't. 
I can ping my website address in terminal and I can upload via terminal but I cannot access it in browser both NAT and IP address. Surge doesn't have a contact where to write the issues, I hope they'll read here. But here is another issue about their services being down and unreliable : https://github.com/sintaxi/surge/issues/513  maybe it's time to change the hosting provider. For me it's bad situation as I have their free 3rd level domain and as hobby photographer I put the website address on my photos.

**Comment by McSloverd** [comment]
Surge main site was down due to whatever reason they have put out but that is not the hosted websites. The main site is on a different server with all the hosted websites. Hosted websites, as what we use custom domain name indicates, is located with domain na-west1.surge.sh. And I bet the problem is here. Ping result of your own website has very little to do with the problem since what you have actually pinged, is the na-west1.surge.sh (the main server), not your particular website. You website is more like a container that lives behind the na-west1.surge.sh. What I believe is that the routing / forwarding layer of surge is broken because the CLI upload is no problem (which means the backend of the service is running and it uses username as an identifier to tell whose website is in which container) and the pinging is no problem (which mean the 'physical' server is running). 

Will they see this? Of course! They must know this at the very begining.

Why this is happend? Maybe something related to the down time of the main server. Upgrade or something. Or something happened to the owner of this awsome service.

Should we look for alternatives? You should have done this long before. Surge is a free service. There is no guarantee or what so ever about free service, and they shouldn't. If you are looking for free hosting, then you should seek redundency yourself. I know I did because I have been using lots of free services online and all ended up with broken service, even for Google. Surge, Netlify, Vercel.... run you domain on Cloudflare, setup automation to redirect to another service when one is broken.

**Comment by boson-higgs** [comment]
@McSloverd If that was meant to be reply to my comment then I am not as stupid as you think. 
1) I know and tried lot of alternatives, so you really do not have to tell me what I should do like to little kid. I found Surge just cca 10 months ago as I liked the CLI uploading. I read all the issues just this week and now thinking if I have put my trust into good hands but I can handle that myself, don't worry. 
2) Of course free services have no guarantee - that's why I don't expect somebody from Surge reading and trying to fix it, but if you want to talk about other services, I didn't notice widely used services being down for several days almost 1 week and repeatedly, it was usually max. several hours.

**Comment by McSloverd** [comment]
@boson-higgs why on earth would you think that I thought you were stupid? If that is true, would you say that lot to some one you think who is stupid? Jee....that anger. I have re-edited my reply and swapped all (you, your, yourself) into (we, our, ourselves), hopefully that makes "we" feel better.

**Comment by akump** [comment]
Has this even been acknowledged yet?

**Comment by theadanielskocher** [comment]
My website is back up and running. How about you?

**Comment by kaijudev** [comment]
> My website is back up and running. How about you?

Mine started working yesterday again but now I'm getting 503 error. Haven't redeployed or anything

**Comment by sintaxi** [comment]
We are in the process of cutting over to new hardware in the SFO region.

**Comment by rtanglao** [comment]
hi @sintaxi aka Brock :-) rolandtanglao.com doesn't work i get the `project not found` error. Seems to be erratic?!? Please let me know if i can help debug this. see https://github.com/rtanglao/rtDOTcom/issues/18

**Comment by sintaxi** [comment]
@rtanglao peculiar issue. Looking into it.

**Comment by sintaxi** [comment]
@rtanglao the issue is fixed after rollback was made to the network layer that handles the communication from our deployment servers and our edge nodes. The issue is related to either a timeout mechanism that was added or its a payload size issue. Thanks for the report.

**Comment by rtanglao** [comment]
Thanks Brock! I guess it's time to close this issue :-) !

**Comment by NesrinJebali** [comment]
i deployed my site a few weeks ago and it works fine , but yesterday , i try to open my site "https://smarttechmahdia.surge.sh/" and  nothing , i redployed it a few times but also nothing , what should i do

**Comment by sintaxi** [comment]
Investigating the issue.
