### ISSUE TITLE
Connection timeout for both my sites all day

### ISSUE THREAD

**Issue by mfncooper** [sintaxi/surge#535]
I have been unable to reach either of my sites on surge.sh all day today. I can ping them successfully, but the sites time out when attempting to reach them in a browser or via wget. Both site names resolve to 138.197.235.123.

I'm creating an issue here because I do not use Twitter / X, and the Chat feature on the website (https://surge.sh/help/chat) is broken and shows only a Heroku box with "There's nothing here, yet." in it.

**Comment by schandler88** [comment]
I also have been experiencing the same thing on all my surge sites!

**Comment by vhongtuanha** [comment]
It's the same for me

**Comment by sintaxi** [comment]
Thx for the heads up. Looking into it.

**Comment by student020341** [comment]
My surge sites have been down since Thursday, thought it was just me since there was no mention of it. Is there an outage tracker for this kind of thing?

**Comment by StevenGFX** [comment]
I have over a hundred sites. I think only a handful are working. 😅

**Comment by mfncooper** [comment]
My sites are working now, but I'll leave this open until the other people who've added their voices here can verify that theirs are too.

As @student020341 intimates, it would be good to have an outage tracker for this kind of thing, or at least a status page. The Help page on the surge.sh website says "We’re available to answer questions on Twitter at @surge_sh or via chat", but many people do not use Twitter / X, and the Chat function simply doesn't work.

**Comment by student020341** [comment]
Just checked, mine are up now, thanks

> many people do not use Twitter / X

I don't, and due to changes they've made, I could not view the surge page to see if anyone else was having issues or if there was an official announcement. I thought maybe something expired and was having a hard time automatically coming back online so I pushed one of my sites again and the cli said that succeeded but it remained down. Maybe some kind of outage detection could be built into the cli itself! that would be interesting
