### ISSUE TITLE
teardown not removing files

### ISSUE THREAD

**Issue by rillian** [sintaxi/surge#68]
I'm having trouble removing files I inadvertently published with surge. I did something like:
```
vim index.html
npm install surge
node_modules/.bin/surge . // oops, it uploaded MB of local node modules...
ctrl-c
surge teardown $domain
mkdir www
mv index.html www/
echo $domain > www/CNAME
surge www/ // still propagates previously uploaded node_modules to cdn
// wait for it to finish
surge teardown $domain
surge www // reports propagating only changed files
// files from node_modules are still accessible
```
see http://educated-kittens.surge.sh/node_modules/surge/README.md for example

**Comment by silentrob** [comment]
So the Readme in question is 404'ing.

Im curious to know when you ctrl-c'ed your app. Internally, we fully abort within the first upload stage and will continue to publish (propagate to the CDN) behind the scenes, should you abort during that stage,

It could have been a race condition as well.

**Comment by sintaxi** [comment]
Hosting surge on surge. Nice :)

I think things are cleared up now. Though we didn't do anything on our end.

**Comment by rillian** [comment]
Aha. Browser cache, I guess. Can't get it on the command line, browser still returns the file.

Cache-Control: public, max-age=31536000

Erring on the side of information freedom, I guess?

I think the bit where it resumes an interrupting propagation to the cdn even when the files aren't part of the current surge is a real bug, but the immediate issue I was concerned about is in fact ok. Thanks for the help!

**Comment by sintaxi** [comment]
@rillian You mind me ask what browser you are using? 

The Cache-Control directive shouldn't matter because the browser uses the Etag to validate the cache. Our edge nodes could have the results cached for a few minutes though so the server is continuing to validate the request. You can test this by opening dev tools and seeing if the server is responding with a 304 or if a request isn't going to the server at all.

I'll check to make sure our invalidation calls are being sent to the edge nodes.
