### ISSUE TITLE
SSL certificate on custom domain with Surge?

### ISSUE THREAD

**Issue by AVGP** [sintaxi/surge#85]
I've read the website and searched the issues here, but couldn't find an answer.

I am running on a custom domain and wonder if I can add my SSL certificate with Surge.sh somehow?

**Comment by sintaxi** [comment]
Surge supports this but its currently an undocumented feature because we plan to charge for this. Until then weeeee!

Simply run `surge ssl --pem path/to/pem/file.pem --domain example.com` and you are good to go. 

If you need assistance with putting together your PEM file I suggest asking for help in the slack channel. https://surge.sh/help/chat

**Comment by AVGP** [comment]
Thanks for the quick and positive response :)

**Comment by trevorwhealy** [comment]
Hey is this still possible?
